services:
  database:
    image: getsreya/converse-db
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    networks:
      - spring_net

    volumes:
      - mysql-data:/var/lib/mysql


  backend: 
    image: getsreya/converse-backend
    depends_on:
      - database
    restart: on-failure
    ports:
      - "8070:8070"
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/conversedb?allowPublicKeyRetrieval=true
    networks:
      - spring_net
      - frontend_net
    
    
  frontend:
    image: getsreya/converse-frontend
    ports:
      - 3000:3000
    networks:
      - frontend_net

networks:
  spring_net:
  frontend_net:

volumes:
  mysql-data: